// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYGBnf78kHmbkY1OrUQerVMlw5ykWOhTY',
    appId: '1:1086027206543:web:a8fd0c846c8ad4985b45fa',
    messagingSenderId: '1086027206543',
    projectId: 'akhanddeep-solar',
    authDomain: 'akhanddeep-solar.firebaseapp.com',
    databaseURL: 'https://akhanddeep-solar-default-rtdb.firebaseio.com',
    storageBucket: 'akhanddeep-solar.firebasestorage.app',
    measurementId: 'G-XQL3F1LM19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgRXHrNk2mbbdJcfpXVsoJ3gwX9W3AnAk',
    appId: '1:1086027206543:android:9aced963ad3b95845b45fa',
    messagingSenderId: '1086027206543',
    projectId: 'akhanddeep-solar',
    databaseURL: 'https://akhanddeep-solar-default-rtdb.firebaseio.com',
    storageBucket: 'akhanddeep-solar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGpru8mN_sIL90dHPpGs0Xnd4EO7j8cjU',
    appId: '1:1086027206543:ios:4bb8e61fa5bbecd05b45fa',
    messagingSenderId: '1086027206543',
    projectId: 'akhanddeep-solar',
    databaseURL: 'https://akhanddeep-solar-default-rtdb.firebaseio.com',
    storageBucket: 'akhanddeep-solar.firebasestorage.app',
    iosBundleId: 'com.example.akhanddeep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGpru8mN_sIL90dHPpGs0Xnd4EO7j8cjU',
    appId: '1:1086027206543:ios:4bb8e61fa5bbecd05b45fa',
    messagingSenderId: '1086027206543',
    projectId: 'akhanddeep-solar',
    databaseURL: 'https://akhanddeep-solar-default-rtdb.firebaseio.com',
    storageBucket: 'akhanddeep-solar.firebasestorage.app',
    iosBundleId: 'com.example.akhanddeep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYGBnf78kHmbkY1OrUQerVMlw5ykWOhTY',
    appId: '1:1086027206543:web:f88e225f640152095b45fa',
    messagingSenderId: '1086027206543',
    projectId: 'akhanddeep-solar',
    authDomain: 'akhanddeep-solar.firebaseapp.com',
    databaseURL: 'https://akhanddeep-solar-default-rtdb.firebaseio.com',
    storageBucket: 'akhanddeep-solar.firebasestorage.app',
    measurementId: 'G-8ZZ161906J',
  );
}
